linters-settings:
  tagliatelle:
    case:
      rules:
        json: goCamel


linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - nlreturn
    - ireturn
    - gochecknoglobals
    - forcetypeassert
    - exhaustivestruct
    - exhaustruct
    - wsl
    - gosec
    - gochecknoinits
    - funlen

issues: {}

run:
  timeout: 5m
